# Generated by Django 3.1.7 on 2021-03-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('Fathr_name', models.CharField(max_length=225)),
                ('House_no', models.CharField(max_length=225)),
                ('Qualification', models.CharField(max_length=225)),
                ('skills', models.CharField(max_length=225)),
                ('emailid', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
